/** Isolated, read-only visual fixtures. Never connects to a real EnergyIQ API. */
import http from 'node:http';
const period = { from: '2026-09-01', toExclusive: '2026-09-12' };
const project = { id: 'ui-demo', workspaceId: 'ui-demo', name: 'Harbour Office · Demo', status: 'published', timezone: 'Asia/Singapore' };
const reports = ['Weekly energy review', 'After-hours consumption', 'Cooling load investigation'].map((title,i) => ({id:`report-${i}`, title:`${title} · Demo`, version:i+1, category:i===0?'scheduled':'custom', kind:'report', period, createdAt:'2026-09-12T08:00:00Z', finishedAt:'2026-09-12T08:00:00Z'}));
const reportHtml = `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:40px;color:#273e32;font:16px/1.7 system-ui;background:#fff}h1{font-size:34px;line-height:1.2;letter-spacing:-.03em}h2{font-size:21px;margin-top:38px}p{color:#526559}.notice{background:#edf3ea;padding:12px;font-size:13px}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #dce5dc;padding:12px 4px}@media(max-width:500px){body{padding:22px}h1{font-size:28px}}</style></head><body><p class="notice">Illustrative preview · synthetic data</p><h1>Weekly energy review</h1><p>Harbour Office<br>1–11 September 2026 · Singapore</p><h2>Focus on after-hours loads</h2><p>This sample demonstrates report typography and layout. It is not an analysis of a real project.</p><table><tr><th>Area</th><th>Review focus</th></tr><tr><td>Office floors</td><td>Operating schedules</td></tr><tr><td>Cooling</td><td>After-hours operation</td></tr><tr><td>Common areas</td><td>Lighting schedules</td></tr></table><h2>Next steps</h2><p>Check the project’s operating calendar and inspect meter readings before drawing conclusions.</p></body></html>`;
const settings = {contextNotes:'Illustrative office project for visual review only.', fileRefIds:[],useProjectData:true,skill:'',revision:1,frequency:'off',localHour:8,scheduledPrompt:'',timezone:'Asia/Singapore'};
const overview = {settings,files:[],sessions:[{id:'demo-chat',createdAt:'2026-09-12T08:00:00Z'}],runs:[{id:'report-0',sessionId:'demo-chat',status:'succeeded',kind:'report',hasReport:true,prompt:'Review energy use and prepare a weekly report.',answer:'## Your report is ready\n\nThis is an illustrative preview. Use the report alongside your project data to review operating schedules and investigate unusual loads.\n\n| Area | Review focus | Status |\n| --- | --- | --- |\n| Office floors | Operating schedules | Needs confirmation |\n| Cooling | After-hours operation | Review readings |',period,createdAt:'2026-09-12T08:00:00Z'}],projectData:{status:'connected',actualLastIntervalEnd:'2026-09-11T16:00:00Z'},periodOptions:{defaultPeriod:period,availablePeriod:period}};
const library = {reports,canChat:true,artifacts:[],skills:[{name:'Energy investigation',version:'v1',scope:'general',category:'analysis',content:'Compare consumption across comparable periods. Check coverage and operating schedules before explaining changes.'},{name:'Office report',version:'v2',scope:'project',category:'presentation',projectId:'ui-demo',content:'Present findings in clear English. Reference the selected period and separate observations from suggested actions.'},{name:'Meter quality review',version:'v1',scope:'general',category:'analysis',content:'Inspect missing readings and source continuity before comparing meters.'}],tools:[{name:'run_sql_readonly',description:'Query project data with read-only SQL.'},{name:'read_file',description:'Read files attached to the project.'}]};
const setup = {project:{...project,has_unpublished_changes:false},draft:{revision:3,updated_at:'2026-09-12T08:00:00Z',document:{project,tiers:[{id:'floor',alias:'Floor'}],nodes:[{id:'level1',name:'Level 1',tier_definition_id:'floor',area_sqm:840,occupant_count:55},{id:'level2',name:'Level 2',tier_definition_id:'floor',area_sqm:760,occupant_count:42}],meter_mapping:{rows:[{id:'cooling',display_name:'Air conditioning',scope_id:'level1',resource:'electricity',category:'aircon',aggregation_usage:'official',meter_role:'component'},{id:'lights',display_name:'Office lighting',scope_id:'level1',resource:'electricity',category:'light',aggregation_usage:'official',meter_role:'component'}],virtual_meters:[]}}}};
export function fixture(path, workspaceId = "ui-demo") {
 if(path.endsWith('/admin/organisations')) return {organisations:[{id:'ui-demo',name:'Visual preview · synthetic data',projects:[project]}]};
 if(path.includes('access-context')) return {role:'admin',user:{id:'ui-review-admin'},activeWorkspaceId:workspaceId,workspaces:[{id:'ui-demo',name:'Visual preview · synthetic data',kind:'customer',disabled:false},{id:'ui-demo-secondary',name:'Second customer · Demo',kind:'customer',disabled:false}],projects:workspaceId==='ui-demo'?[project]:[{...project,id:'ui-demo-school',workspaceId:'ui-demo-secondary',name:'School · Demo'}]};
 if(path.includes('identit')) return {users:[]};
 if(path.includes('/setup')) return setup;
 if(path.includes('operational-policies')) return {published:null,pending:null,tariffRevisions:[],operatingCalendarRevisions:[]};
 if(path.includes('/output/')) return {content:reportHtml};
 if(path.includes('/events')) return {events:[]};
 if(path.includes('report-library')) return library;
 if(path.includes('report-agent')) return overview;
 return {};
}
if(process.argv.includes('--serve')) http.createServer((req,res)=>{
 res.setHeader('Access-Control-Allow-Origin','http://127.0.0.1:3185');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, X-Workspace-Id, X-User-Id, X-User-Name');
 if(req.method==='OPTIONS'){res.writeHead(204);res.end();return;}
 res.setHeader('Content-Type','application/json');
 if(req.method!=='GET'){res.writeHead(405);res.end(JSON.stringify({success:false,error:{code:'PREVIEW_ONLY',message:'Read-only visual preview. Actions are disabled in the fixture server.'}}));return;}
 res.end(JSON.stringify({success:true,data:fixture(req.url,req.headers["x-workspace-id"] || "ui-demo")}));
}).listen(3186,'127.0.0.1',()=>console.log('Read-only UI fixtures: http://127.0.0.1:3186'));

