import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3185/energyiq/reports?projectId=ui-demo&sessionId=new',{waitUntil:'networkidle'});
const recent=page.getByRole('region',{name:'Recent project reports'});
assert.equal(await recent.getByRole('link',{name:/Preview/}).count(),2);
await recent.getByRole('button',{name:'Show more reports'}).click();
assert.equal(await recent.getByRole('link',{name:/Preview/}).count(),3);
await recent.getByRole('button',{name:'Show fewer'}).click();
const input=page.getByRole('textbox',{name:'Report instructions',exact:true});
await input.fill('Preserve my draft');
await page.screenshot({path:'artifacts/ui-preview/recent-reports-desktop.png'});
await recent.getByRole('link',{name:/Preview Weekly/}).click();
await page.getByRole('complementary',{name:'File preview'}).waitFor();
assert.equal(await input.inputValue(),'Preserve my draft');
assert.match(page.url(),/sessionId=new/);
assert.equal(await page.getByText('Using the selected report as context').count(),0);
await page.getByRole('button',{name:'Close preview'}).click();
await page.getByRole('region',{name:'Recent reports to explore'}).getByRole('button').first().click();
await page.getByRole('complementary',{name:'File preview'}).waitFor();
await page.getByRole('button',{name:'Expand',exact:true}).click();
await page.getByRole('dialog',{name:'File preview'}).waitFor();
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Close preview'}).click();
await page.setViewportSize({width:390,height:844});
await recent.getByRole('link',{name:/Preview Weekly/}).click();
await page.getByRole('dialog',{name:'File preview'}).waitFor();
await page.screenshot({path:'artifacts/ui-preview/recent-reports-mobile-preview.png'});
await page.keyboard.press('Escape');
assert.equal(await input.inputValue(),'Preserve my draft');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);
writeFileSync('artifacts/ui-preview/recent-reports.json',JSON.stringify({checks:['two reports and expansion','sidebar preview preserves draft and route','start-page preview','desktop expand and Escape','mobile modal and draft','no overflow or page errors']},null,2));
await browser.close();
