"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { configApi } from "../../../lib/config-api";
import { shiftDate } from "../_components/report-period";

type Task = { id:string; projectName:string; title:string; actor:string; origin:string; status:string; createdAt:string; startedAt:string|null; finishedAt:string|null; conversationHref:string|null; reportHref:string|null };
type List = {items:Task[];total:number;page:number;pageSize:number;projects:{id:string;name:string}[];observedAt:string};
type Detail = Task & {period:{from:string;toExclusive:string};timezone:string;model:string|null;skills:{name:string;version:string|null;source:string}[];data:{snapshot:string|null;hierarchy:string|null;mapping:string|null};failureReason:string|null;events:{time:string;label:string;isError:boolean}[];sessionId:string|null};
const labels:Record<string,string>={queued:"Queued",running:"Running",succeeded:"Completed",failed:"Failed",interrupted:"Interrupted",cancelled:"Stopped"};
const control="rounded-lg border border-border bg-surface px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50";
const time=(value:string|null)=>value?new Date(value).toLocaleString("en-SG",{timeZone:"Asia/Singapore",dateStyle:"medium",timeStyle:"short"}):"Not recorded";
export function taskDuration(task:Task,observedAt:string) {
 if(!task.startedAt)return task.status==="queued"?"Not started":"Not recorded";
 const end=task.finishedAt??(["queued","running"].includes(task.status)?observedAt:null);
 if(!end)return "Not recorded";const seconds=Math.max(0,Math.floor((Date.parse(end)-Date.parse(task.startedAt))/1000));
 return Number.isFinite(seconds)?`${Math.floor(seconds/60)}m ${seconds%60}s`:"Not recorded";
}
export function AdminTaskHistory({client=configApi}:{client?:Pick<typeof configApi,"reportTaskHistoryRequest">}) {
 const [project,setProject]=useState("");const [status,setStatus]=useState("");const [origin,setOrigin]=useState("");const [page,setPage]=useState(0);const [revision,setRevision]=useState(0);
 const [data,setData]=useState<List|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 const [selected,setSelected]=useState("");const [detail,setDetail]=useState<Detail|null>(null);const [detailError,setDetailError]=useState("");
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError("");const q=new URLSearchParams({page:String(page),...(project?{projectId:project}:{}),...(status?{status}:{}),...(origin?{origin}: {})});
 client.reportTaskHistoryRequest<List>(`?${q}`,{signal:abort.signal}).then(value=>{if(!abort.signal.aborted)setData(value)}).catch(()=>{if(!abort.signal.aborted){setData(null);setError("Task history could not be loaded. Check your access or refresh to try again.")}}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort();},[client,project,status,origin,page,revision]);
 useEffect(()=>{setDetail(null);setDetailError("");if(!selected)return;const abort=new AbortController();client.reportTaskHistoryRequest<{task:Detail}>(`/${encodeURIComponent(selected)}`,{signal:abort.signal}).then(value=>{if(!abort.signal.aborted)setDetail(value.task)}).catch(()=>{if(!abort.signal.aborted)setDetailError("This task is unavailable or you no longer have access.")});return()=>abort.abort();},[client,selected,revision]);
 function filter(set:(v:string)=>void,value:string){set(value);setPage(0);setSelected("");}
 return <section className="space-y-5" aria-label="Task history">
 <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Task history</h2><p className="mt-1 text-sm text-muted">Report and analysis tasks in projects you manage.</p></div><button className={control} onClick={()=>setRevision(v=>v+1)}>Refresh</button></header>
 <div className="flex flex-wrap gap-3"><label className="grid gap-1 text-sm">Project<select className={control} value={project} onChange={e=>filter(setProject,e.target.value)}><option value="">All managed projects</option>{data?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="grid gap-1 text-sm">Status<select className={control} value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="">All statuses</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="grid gap-1 text-sm">Started by<select className={control} value={origin} onChange={e=>filter(setOrigin,e.target.value)}><option value="">Everyone</option><option value="manual">People</option><option value="automatic">Automatic reports</option></select></label></div>
 {error&&<p role="alert">{error}</p>}{loading?<p role="status">Loading task history…</p>:data&&<><div tabIndex={0} aria-label="Task list, scroll horizontally on smaller screens" className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[640px] text-left text-sm"><caption className="sr-only">Tasks, times in Singapore time</caption><thead className="bg-surface-subtle"><tr>{["Task / project","Started by","Status","Started (SGT)","Duration"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(task=><tr className="border-t border-border" key={task.id}><td className="p-3"><button className="font-semibold underline underline-offset-4" onClick={()=>setSelected(task.id)}>{task.title}</button><div className="mt-1 text-muted">{task.projectName}</div></td><td className="p-3">{task.actor}</td><td className="p-3">{labels[task.status]??"Not recorded"}</td><td className="p-3">{time(task.startedAt)}</td><td className="p-3 whitespace-nowrap">{taskDuration(task,data.observedAt)}</td></tr>)}</tbody></table>{!data.items.length&&<p className="p-6 text-sm text-muted">No tasks match these filters.</p>}</div><nav aria-label="Task pages" className="flex items-center justify-between gap-3"><button className={control} disabled={page===0} onClick={()=>{setPage(v=>v-1);setSelected("")}}>Previous</button><span className="text-sm">Page {page+1} of {Math.max(1,Math.ceil(data.total/data.pageSize))} · {data.total} {data.total === 1 ? "task" : "tasks"}</span><button className={control} disabled={(page+1)*data.pageSize>=data.total} onClick={()=>{setPage(v=>v+1);setSelected("")}}>Next</button></nav><p className="text-xs text-muted">Status checked {time(data.observedAt)}. Refresh for updates.</p></>}
 {selected&&<section aria-label="Task details" className="rounded-xl border border-border p-5 space-y-4"><div className="flex justify-between"><h3 className="font-semibold">{detail?.title??"Task details"}</h3><button className={control} onClick={()=>setSelected("")}>Close details</button></div>{detailError?<p role="alert">{detailError}</p>:!detail?<p role="status">Loading task details…</p>:<>
 <p>{detail.projectName} · {labels[detail.status]}</p><p className="text-sm">{detail.period.from} – {shiftDate(detail.period.toExclusive,-1)} · {detail.timezone}</p>
 <dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted">Model used</dt><dd>{detail.model??"Not recorded"}</dd></div><div><dt className="text-muted">Submitted</dt><dd>{time(detail.createdAt)}</dd></div><div><dt className="text-muted">Started / finished</dt><dd>{time(detail.startedAt)} / {time(detail.finishedAt)}</dd></div><div><dt className="text-muted">Skill versions supplied</dt><dd>{detail.skills.length?detail.skills.map((s,i)=><div key={i}>{s.name} · {s.version??"Version private"}</div>):"Not recorded"}</dd></div></dl>
 {detail.failureReason&&<p role="alert" className="rounded-lg bg-surface-subtle p-3">{detail.failureReason}</p>}
 <div className="flex flex-wrap gap-3">{detail.conversationHref?<Link className={control} href={detail.conversationHref}>Open conversation</Link>:<span className="text-sm text-muted">Conversation private to its author</span>}{detail.reportHref&&<Link className={control} href={detail.reportHref}>Open report</Link>}</div>
 <h4 className="font-semibold text-sm">Recorded activity</h4>{detail.events.length?<ol className="space-y-2 text-sm">{detail.events.map((event,i)=><li key={i} className="flex flex-wrap justify-between gap-2"><span>{event.label}{event.isError?" · Needs attention":""}</span><time className="text-muted">{time(event.time)}</time></li>)}</ol>:<p className="text-sm text-muted">No activity recorded.</p>}
 <p className="text-xs text-muted">Latest 50 recorded milestones. Supplied Skills do not prove how the model applied them. Private messages and tool contents are not included.</p>
 <details className="text-sm"><summary className="cursor-pointer">Technical details</summary><dl className="mt-3 space-y-2 break-all">{Object.entries({"Task ID":detail.id,"Session ID":detail.sessionId,"Data snapshot":detail.data.snapshot,"Hierarchy version":detail.data.hierarchy,"Meter mapping version":detail.data.mapping}).map(([label,value])=><div key={label}><dt className="text-muted">{label}</dt><dd>{value??"Not recorded"}</dd></div>)}</dl></details>
 </>}</section>}
 </section>;
}
