import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {it,expect} from 'vitest';
import {ActionStore} from './action-store.js';
import {ActionProgressDrafts} from './action-progress-drafts.js';
const scope={workspaceId:'w',projectId:'p',userId:'u'};
function setup(){const db=new DatabaseSync(':memory:');const actions=new ActionStore(db);const action=actions.create(scope,{sourceReportId:'r',title:'Lights',recommendation:'Review lights',meterIds:['light'],baseline:{from:'2026-08-01',toExclusive:'2026-09-01',snapshotId:'s'},idempotencyKey:'a',visibility:'project'});return {db,actions,action,store:new ActionProgressDrafts(db)};}
it('keeps interpretation separate from execution and confirms once with original evidence',()=>{const {db,actions,action,store}=setup();try{const d=store.start(scope,action.id,{requestId:randomUUID(),text:'We turned off lights on September 1 at 8pm.'},randomUUID);store.finish(scope,action.id,d.runId,{type:'implemented',effectiveAt:'2026-09-01T20:00:00+08:00',summary:'Lights turned off',questions:[]});expect(actions.events(scope,action.id)).toEqual([]);store.confirm(scope,action.id,d.id);store.confirm(scope,action.id,d.id);expect(actions.events(scope,action.id)).toHaveLength(1);expect(actions.events(scope,action.id)[0]?.details).toBe(d.text);expect(store.list({...scope,userId:'other'},action.id)).toEqual([]);}finally{db.close();}});
it('requires clarification and rejects changed action revisions',()=>{const {db,actions,action,store}=setup();try{const d=store.start(scope,action.id,{requestId:randomUUID(),text:'Maybe tomorrow'},randomUUID);store.finish(scope,action.id,d.runId,{type:null,effectiveAt:null,summary:'Unclear',questions:['When?']});expect(()=>store.confirm(scope,action.id,d.id)).toThrow('CLARIFICATION');const next=store.start(scope,action.id,{requestId:randomUUID(),text:'We did this yesterday at 8pm'},randomUUID);store.finish(scope,action.id,next.runId,{type:'implemented',effectiveAt:'2026-09-01T20:00:00+08:00',summary:'Done',questions:[]});actions.record(scope,action.id,{revision:1,requestId:'pause',type:'paused',effectiveAt:'2026-09-02T00:00:00Z',details:'Paused'});expect(()=>store.confirm(scope,action.id,next.id)).toThrow('REVISION');}finally{db.close();}});
it('rolls back failed enqueue and rejects changed idempotency payload',()=>{const {db,action,store}=setup();try{const input={requestId:randomUUID(),text:'Plan'};expect(()=>store.start(scope,action.id,input,()=>{throw Error('queue');})).toThrow('queue');expect(store.list(scope,action.id)).toEqual([]);store.start(scope,action.id,input,randomUUID);expect(()=>store.start(scope,action.id,{...input,text:'Other'},randomUUID)).toThrow('CONFLICT');}finally{db.close();}});
