/** @vitest-environment happy-dom */
import React, {act} from "react";
import {createRoot, type Root} from "react-dom/client";
import {beforeEach,afterEach,it,expect,vi} from "vitest";
const state=vi.hoisted(()=>({role:"admin",signOut:vi.fn(),push:vi.fn()}));
vi.mock("next/navigation",()=>({useRouter:()=>({push:state.push})}));
vi.mock("next/dynamic",()=>({default:()=>({embedded}:{embedded:boolean})=><div data-embedded={embedded}>Existing admin console</div>}));
vi.mock("./energyiq-access",()=>({useEnergyIqAccess:()=>({access:{role:state.role,activeWorkspaceId:"w",workspaces:[{id:"w",name:"Office"}]}})}));
vi.mock("../../data-tasks/data-task-identity",()=>({useDataTaskIdentity:()=>({currentUser:{userId:"u1",displayName:"Jamie",email:"jamie@example.test"},signOut:state.signOut,error:null}),DataTaskAvatar:()=> <span>J</span>}));
import {EnergyIqAccountMenu} from "./energyiq-account-menu";
let host:HTMLDivElement;let root:Root;
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;vi.stubGlobal("React",React);state.role="admin";state.signOut.mockReset();host=document.createElement("div");document.body.append(host);root=createRoot(host);vi.spyOn(HTMLDialogElement.prototype,"showModal").mockImplementation(function(){this.setAttribute("open","");});vi.stubGlobal("requestAnimationFrame",(cb:()=>void)=>{cb();return 0;});});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function click(label:string){await act(async()=>{const el=[...document.querySelectorAll<HTMLButtonElement>("button")].find(el=>(el.getAttribute("aria-label")||el.textContent)===label)!;el.click();});}
it("shows personal details and sign out for users without an admin entry",async()=>{state.role="user";await act(async()=>root.render(<EnergyIqAccountMenu collapsed={false}/>));await click("Open account menu");expect(document.querySelector('[role=menu]')?.textContent).not.toContain("Admin console");await click("Personal information");expect(document.querySelector("dialog")?.textContent).toContain("jamie@example.test");expect(document.querySelector("dialog")?.textContent).toContain("Office");await click("Close Personal information");expect(document.activeElement?.getAttribute("aria-label")).toBe("Open account menu");await click("Open account menu");await click("Sign out");expect(state.signOut).toHaveBeenCalledOnce();});
it("opens the existing console embedded and removes it if admin access is lost",async()=>{await act(async()=>root.render(<EnergyIqAccountMenu collapsed={false}/>));await click("Open account menu");await click("Admin console");expect(document.querySelector('[data-embedded=true]')).not.toBeNull();state.role="user";await act(async()=>root.render(<EnergyIqAccountMenu collapsed={false}/>));expect(document.querySelector("dialog")).toBeNull();});
it("supports collapsed navigation, arrow keys and Escape",async()=>{await act(async()=>root.render(<EnergyIqAccountMenu collapsed/>));await click("Open account menu");expect(document.activeElement?.textContent).toBe("Personal information");await act(async()=>document.activeElement?.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown",bubbles:true})));expect(document.activeElement?.textContent).toBe("Admin console");await act(async()=>document.activeElement?.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true})));expect(document.querySelector('[role=menu]')).toBeNull();expect(document.activeElement?.getAttribute("aria-label")).toBe("Open account menu");});
it("opens the user guide from the account menu",async()=>{state.push.mockReset();await act(async()=>root.render(<EnergyIqAccountMenu collapsed={false}/>));await click("Open account menu");await click("User guide");expect(state.push).toHaveBeenCalledWith("/energyiq/guide");expect(document.querySelector('[role=menu]')).toBeNull();});
