/** @vitest-environment happy-dom */
import React, { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { beforeEach, afterEach, describe, it, expect, vi } from "vitest";
import type { EnergyAccessContextDto, EnergyProjectDto } from "../../../lib/config-api";
const api = vi.hoisted(()=>({getEnergyAccessContext:vi.fn(),moveEnergyAdminProject:vi.fn(),createEnergyAdminOrganisation:vi.fn(),setEnergyAdminProjectArchived:vi.fn(),deleteEnergyAdminProject:vi.fn(),deleteEnergyAdminOrganisation:vi.fn()}));
vi.mock("../../../lib/config-api",()=>({configApi:api}));
import { ProjectSwitcher } from "./project-switcher";
let container: HTMLDivElement, root: Root;
const project = (id:string, workspaceId:string, status:EnergyProjectDto["status"]="published"):EnergyProjectDto=>({id,name:id,workspaceId,status,timezone:"Asia/Singapore"});
const current=project("Office","a");
const access:EnergyAccessContextDto={role:"admin",user:{id:"u"},activeWorkspaceId:"a",projects:[current],workspaces:[{id:"a",name:"Customer A",kind:"customer",disabled:false},{id:"b",name:"Customer B",kind:"customer",disabled:false},{id:"c",name:"Disabled customer",kind:"customer",disabled:true}]};
const onSelect=vi.fn(),onCreate=vi.fn();
beforeEach(()=>{vi.stubGlobal("React",React);vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT",true);container=document.createElement("div");document.body.append(container);root=createRoot(container);onSelect.mockReset();onCreate.mockReset();api.getEnergyAccessContext.mockReset();api.moveEnergyAdminProject.mockReset().mockResolvedValue({organisations:[]});api.createEnergyAdminOrganisation.mockReset();api.setEnergyAdminProjectArchived.mockReset().mockResolvedValue({organisations:[]});api.deleteEnergyAdminProject.mockReset().mockResolvedValue({organisations:[]});api.deleteEnergyAdminOrganisation.mockReset().mockResolvedValue({organisations:[]});api.getEnergyAccessContext.mockResolvedValue({...access,activeWorkspaceId:"b",projects:[project("School","b"),project("Draft","b","draft"),project("Wrong tenant","c")]});});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.unstubAllGlobals();});
async function open(role:"admin"|"user"="admin") {await act(async()=>root.render(<ProjectSwitcher access={{...access,role}} activeProject={current} projects={[current]} allowDrafts={role==="admin"} allowArchived={false} busy={false} canCreate={role==="admin"} onSelect={onSelect} onCreate={onCreate}/>));await act(async()=>container.querySelector<HTMLButtonElement>('[aria-label="Choose project"]')!.click());}
describe("single project picker",()=>{
 it("choosing the current project closes without resetting the current conversation",async()=>{await open();await act(async()=>container.querySelector<HTMLButtonElement>("button[data-project]")!.click());expect(onSelect).not.toHaveBeenCalled();expect(container.querySelector("dialog")).toBeNull();});
 it("has one entry, loads only authorised customers, and selects a specific project",async()=>{await open();expect(api.getEnergyAccessContext).toHaveBeenCalledTimes(1);expect(api.getEnergyAccessContext).toHaveBeenCalledWith(expect.objectContaining({workspaceId:"b"}));expect(container.textContent).not.toContain("Wrong tenant");expect(container.textContent).not.toContain("Disabled customer");await act(async()=>[...container.querySelectorAll<HTMLButtonElement>("button[data-project]")].find(b=>b.textContent?.startsWith("School"))!.click());expect(onSelect).toHaveBeenCalledWith("b","School");expect(container.querySelector("dialog")).toBeNull();});
 it("does not offer draft projects or create for a normal reader",async()=>{await open("user");expect(container.textContent).not.toContain("Draft");expect(container.textContent).not.toContain("New project");});
 it("searches customer and project names and supports keyboard focus",async()=>{await open();const input=container.querySelector<HTMLInputElement>("input")!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(input,"School");input.dispatchEvent(new Event("input",{bubbles:true}));});expect(container.querySelectorAll("button[data-project]")).toHaveLength(1);await act(async()=>input.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown",bubbles:true})));expect(document.activeElement?.textContent).toContain("School");});
 it("keeps the picker open on switching failure and retries loading errors",async()=>{api.getEnergyAccessContext.mockRejectedValueOnce(new Error("network"));await open();expect(container.textContent).toContain("Retry");await act(async()=>[...container.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent?.includes("Retry"))!.click());onSelect.mockRejectedValueOnce(new Error("denied"));await act(async()=>[...container.querySelectorAll<HTMLButtonElement>("button[data-project]")].find(b=>b.textContent?.startsWith("School"))!.click());expect(container.querySelector('[role="alert"]')?.textContent).toContain("Unable to switch");expect(container.querySelector("dialog")).not.toBeNull();});
 it("retains the admin create action scoped to the current customer",async()=>{await open();const create=[...container.querySelectorAll<HTMLButtonElement>("footer button")][0]!;expect(create.textContent).toContain("Customer A");await act(async()=>create.click());expect(onCreate).toHaveBeenCalledOnce();});
 it("lets an admin drag a project onto another customer and confirm in a modal",async()=>{await open();const office=[...container.querySelectorAll<HTMLButtonElement>("button[data-project]")].find(b=>b.textContent?.startsWith("Office"))!;expect(office.getAttribute("draggable")).toBe("true");await act(async()=>drag(office,"dragstart"));const target=container.querySelector<HTMLElement>('section[aria-label="Customer B"]')!;await act(async()=>drag(target,"dragover"));expect(target.textContent).toContain("Drop to move here");await act(async()=>drag(target,"drop"));const modal=container.querySelector<HTMLDialogElement>('dialog[aria-labelledby="move-project-title"]')!;expect(modal.textContent).toContain("Move Office");expect(modal.textContent).toContain("Customer A");expect(modal.textContent).toContain("Customer B");expect(api.moveEnergyAdminProject).not.toHaveBeenCalled();await act(async()=>modal.querySelector<HTMLButtonElement>("button[type=submit]")!.click());expect(api.moveEnergyAdminProject).toHaveBeenCalledWith("Office",{organisationId:"b"});expect(onSelect).toHaveBeenCalledWith("b","Office");});
 it("names and creates a new customer from the modal when dropped on the new-customer zone",async()=>{api.createEnergyAdminOrganisation.mockResolvedValue({id:"new-org"});await open();const office=[...container.querySelectorAll<HTMLButtonElement>("button[data-project]")].find(b=>b.textContent?.startsWith("Office"))!;await act(async()=>drag(office,"dragstart"));const zone=[...container.querySelectorAll<HTMLElement>("div")].find(el=>el.textContent==="Drop here to create a new client for it")!;await act(async()=>drag(zone,"dragover"));await act(async()=>drag(zone,"drop"));const modal=container.querySelector<HTMLDialogElement>('dialog[aria-labelledby="move-project-title"]')!;const input=modal.querySelector<HTMLInputElement>("input")!;expect(input.value).toBe("Office");await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(input,"Office Co");input.dispatchEvent(new Event("input",{bubbles:true}));});expect(modal.textContent).toContain("Create client and move");await act(async()=>modal.querySelector<HTMLButtonElement>("button[type=submit]")!.click());expect(api.createEnergyAdminOrganisation).toHaveBeenCalledWith({name:"Office Co"});expect(api.moveEnergyAdminProject).toHaveBeenCalledWith("Office",{organisationId:"new-org"});});
 it("cancelling the move modal changes nothing",async()=>{await open();const office=[...container.querySelectorAll<HTMLButtonElement>("button[data-project]")].find(b=>b.textContent?.startsWith("Office"))!;await act(async()=>drag(office,"dragstart"));const target=container.querySelector<HTMLElement>('section[aria-label="Customer B"]')!;await act(async()=>drag(target,"dragover"));await act(async()=>drag(target,"drop"));const modal=container.querySelector<HTMLDialogElement>('dialog[aria-labelledby="move-project-title"]')!;await act(async()=>[...modal.querySelectorAll<HTMLButtonElement>("footer button")].find(b=>b.textContent==="Cancel")!.click());expect(container.querySelector('dialog[aria-labelledby="move-project-title"]')).toBeNull();expect(api.moveEnergyAdminProject).not.toHaveBeenCalled();});
 it("does not let a normal reader drag projects",async()=>{await open("user");const office=[...container.querySelectorAll<HTMLButtonElement>("button[data-project]")].find(b=>b.textContent?.startsWith("Office"))!;expect(office.getAttribute("draggable")).toBe("false");expect(container.textContent).not.toContain("drag a project");});
 it("offers admin actions on each project and customer through row menus",async()=>{const reload=vi.fn();vi.stubGlobal("location",{...window.location,reload});await open();const kebab=container.querySelector<HTMLButtonElement>('button[aria-label="Actions for Office"]')!;await act(async()=>kebab.click());const items=[...container.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')].map(b=>b.textContent);expect(items).toEqual(["Move to another client…","Archive","Delete permanently…"]);await act(async()=>[...container.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')].find(b=>b.textContent==="Archive")!.click());const modal=container.querySelector<HTMLDialogElement>('dialog[aria-labelledby="admin-action-title"]')!;expect(modal.textContent).toContain("Archive Office");await act(async()=>modal.querySelector<HTMLButtonElement>("button[type=submit]")!.click());expect(api.setEnergyAdminProjectArchived).toHaveBeenCalledWith("Office",true);expect(reload).toHaveBeenCalled();expect(container.querySelector('button[aria-label="Actions for Customer A"]')).not.toBeNull();});
 it("only enables permanent project deletion once the exact name is typed",async()=>{vi.stubGlobal("location",{...window.location,reload:vi.fn()});await open();await act(async()=>container.querySelector<HTMLButtonElement>('button[aria-label="Actions for Office"]')!.click());await act(async()=>[...container.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')].find(b=>b.textContent==="Delete permanently…")!.click());const modal=container.querySelector<HTMLDialogElement>('dialog[aria-labelledby="admin-action-title"]')!;const submit=modal.querySelector<HTMLButtonElement>("button[type=submit]")!;expect(submit.disabled).toBe(true);const input=modal.querySelector<HTMLInputElement>("input")!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(input,"Office");input.dispatchEvent(new Event("input",{bubbles:true}));});expect(submit.disabled).toBe(false);await act(async()=>submit.click());expect(api.deleteEnergyAdminProject).toHaveBeenCalledWith("Office","Office");});
 it("moves a project from its menu by choosing the destination in the modal",async()=>{await open();await act(async()=>container.querySelector<HTMLButtonElement>('button[aria-label="Actions for Office"]')!.click());await act(async()=>[...container.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')].find(b=>b.textContent==="Move to another client…")!.click());const modal=container.querySelector<HTMLDialogElement>('dialog[aria-labelledby="move-project-title"]')!;expect(modal.querySelector("select")!.value).toBe("b");await act(async()=>modal.querySelector<HTMLButtonElement>("button[type=submit]")!.click());expect(api.moveEnergyAdminProject).toHaveBeenCalledWith("Office",{organisationId:"b"});});
 it("creates a new customer from the footer",async()=>{vi.stubGlobal("location",{...window.location,reload:vi.fn()});api.createEnergyAdminOrganisation.mockResolvedValue({id:"n"});await open();await act(async()=>[...container.querySelectorAll<HTMLButtonElement>("footer button")].find(b=>b.textContent==="New client")!.click());const modal=container.querySelector<HTMLDialogElement>('dialog[aria-labelledby="admin-action-title"]')!;const input=modal.querySelector<HTMLInputElement>("input")!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(input,"Acme");input.dispatchEvent(new Event("input",{bubbles:true}));});await act(async()=>modal.querySelector<HTMLButtonElement>("button[type=submit]")!.click());expect(api.createEnergyAdminOrganisation).toHaveBeenCalledWith({name:"Acme"});});
 it("shows no admin menus to a normal reader",async()=>{await open("user");expect(container.querySelector('button[aria-haspopup="menu"]')).toBeNull();expect(container.textContent).not.toContain("New client");});
 it("closes when the dimmed area outside the picker is clicked",async()=>{await open();const dialog=container.querySelector("dialog")!;dialog.getBoundingClientRect=()=>({left:100,right:500,top:100,bottom:600,width:400,height:500,x:100,y:100,toJSON(){}}) as DOMRect;await act(async()=>dialog.dispatchEvent(new MouseEvent("click",{bubbles:true,clientX:800,clientY:300})));expect(container.querySelector("dialog")).toBeNull();expect(onSelect).not.toHaveBeenCalled();});
 it("stays open when clicking inside the picker",async()=>{await open();const dialog=container.querySelector("dialog")!;dialog.getBoundingClientRect=()=>({left:100,right:500,top:100,bottom:600,width:400,height:500,x:100,y:100,toJSON(){}}) as DOMRect;await act(async()=>dialog.dispatchEvent(new MouseEvent("click",{bubbles:true,clientX:300,clientY:300})));expect(container.querySelector("dialog")).not.toBeNull();});
});
function drag(element:Element,type:string){const event=new Event(type,{bubbles:true,cancelable:true});Object.defineProperty(event,"dataTransfer",{value:{setData(){},effectAllowed:"",dropEffect:""}});element.dispatchEvent(event);}
